//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Model
{
	public class Company
	{
		public Int64 Id { get; set; }
		public string Title { get; set; }
		public double Share { get; set; }
		public int Period { get; set; }
		public decimal Investment { get; set; }

		public virtual ICollection<Service> Services {get; set;}

		public Company (Int64 id, string title, double share, int period, 
		                decimal investment)
		{
			Id = id;
			Title = title;
			Share = share;
			Period = period;
			Investment = investment;
		}
	}
}