//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Model
{
	public class Competitor
	{
		public Int64 Id { get; set; }
		public string Title { get; set; }
		public double Success_rate { get; set; }

		public Int64 Enterprise_id { get; set; }

		public virtual Enterprise Enterprise { get; set; }

		public Competitor (Int64 id, string title, double success_rate, Int64 enterprise_id)
		{
			Id = id;
			Title = title;
			Success_rate = success_rate;
			Enterprise_id = enterprise_id;
		}
	}
}