//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Model
{
	public class Document
	{
		public Int64 Id { get; set; }
		public string Title { get; set; }
		public string Type { get; set; }
		public int Path { get; set; }

		public virtual ICollection<Enterprise_docs> Enterprise_docs {get; set;}

		public Document (Int64 id, string title, string type, int path)
		{
			Id = id;
			Title = title;
			Type = type;
			Path = path;
		}
	}
}