//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Model
{
	public class Employee
	{
		public Int64 Id { get; set; }
		public string Title { get; set; }
		public double Qualification { get; set; }
		public decimal Salary { get; set; }

		public Int64 Role_id { get; set; }
		public Int64 Enterprise_id { get; set; }

		public virtual Role Role { get; set; }
		public virtual Enterprise Enterprise { get; set; }

		public virtual ICollection<Salary_payment> Salary_payments {get; set;}
		public virtual ICollection<Team_member> Team_members {get; set;}

		public Employee (Int64 id, string title, double qualification, decimal salary, 
		                 Int64 role_id, Int64 enterprise_id)
		{
			Id = id;
			Title = title;
			Qualification = qualification;
			Salary = salary;
			Role_id = role_id;
			Enterprise_id = enterprise_id;
		}
	}
}