//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace Model
{
	public class Enterprise
	{
		public Int64 Id { get; set; }
		public string Title { get; set; }
		public decimal Balance { get; set; }
		public double Stationary { get; set; }
		public Int16? Type { get; set; }

		public Int64 Taxation_id { get; set; }

		public virtual Taxation Taxation { get; set; }

		public virtual ICollection<Asset> Assets {get; set;}
		public virtual ICollection<Competitor> Competitors {get; set;}
		public virtual ICollection<Employee> Employees {get; set;}
		public virtual ICollection<Enterprise_docs> Enterprise_docs {get; set;}
		public virtual ICollection<Equipment> Equipment {get; set;}
		public virtual ICollection<Revenue> Revenues {get; set;}
		public virtual ICollection<Enterprise_equipment> Enterprise_equipment {get; set;}

		public Enterprise (Int64 id, string title, decimal balance, double stationary, 
		                   Int16? type, Int64 taxation_id)
		{
			Id = id;
			Title = title;
			Balance = balance;
			Stationary = stationary;
			Type = type;
			Taxation_id = taxation_id;
		}
		public void CompleteDocuments(MySqlConnection connection)
		{
			//if legal body - complete form #1, if private - form #10
			String form = "";
			if (Type==1) form = System.IO.File.ReadAllText(@"..\Docs\registration_form_1.txt");
			else form = System.IO.File.ReadAllText(@"..\Docs\registration_form_10.txt");

			//Team_memberDAO.InsertTeam_members(connection, new List<Team_member> () { new Team_member(employee_id, project_id)});
		}
	}
}