//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Model
{
	public class Human_resources 
	{
		public Int64 Id { get; set; }
		public int Hours { get; set; }

		public Int64 Role_id { get; set; }
		public Int64 Project_id { get; set; }

		public Role Role { get; set; }
		public Project Project { get; set; }

		public Human_resources (Int64 id, int hours, Int64 role_id, Int64 project_id)
		{
			Id = id;
			Hours = hours;
			Role_id = role_id;
			Project_id = project_id;
		}
	}
}