//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Model
{
	public class Product
	{
		public Int64 Id { get; set; }
		public string Title { get; set; }
		public decimal Price { get; set; }
		public double Quality { get; set; }
		public decimal Prime_cost { get; set; } 

		public Int64 Project_id { get; set; }
		public Project Project { get; set; }

		public Product (Int64 id, string title, decimal price, double quality,
		                decimal prime_cost)
		{
			Id = id;
			Title = title;
			Price = price;
			Quality = quality;
			Prime_cost = prime_cost;
		}

		public Product (Int64 id, string title, decimal prime_cost)
			: this(id,title,0,0,prime_cost)
		{
		}
	}
}
