//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Model
{
	public class Project
	{
		public Int64 Id { get; set; }
		public DateTime Planned_begin_date { get; set; } //Let's not cut words here to 1 letter) at least start, end
		public DateTime Planned_end_date { get; set; }
		public DateTime Real_begin_date { get; set; }
		public DateTime Real_end_date { get; set; }
		public int State { get; set; }
		public decimal Stated_budget { get; set; } 
		public decimal Real_budget { get; set; }

		public virtual ICollection<Human_resources> Human_resources {get; set;}
		public virtual ICollection<Product> Product {get; set;}
		public virtual ICollection<Project_stage> Project_stage {get; set;}
		public virtual ICollection<Employee> Employees {get; set;}
				
		public Project (Int64 id, DateTime planned_begin_date, DateTime planned_end_date,
		                DateTime real_begin_date, DateTime real_end_date, int state, decimal stated_budget, decimal real_budget)
		{		                
			Planned_begin_date = planned_begin_date;
			Planned_end_date = planned_end_date;
			Id = id;
			Real_begin_date = real_begin_date;
			Real_end_date = real_end_date;
			State = state;
			Stated_budget = stated_budget;
			Real_budget = real_budget;
		} //add to all models functions or a class?
	}
}