//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Model
{
	public class Purchase
	{
		public Int64 Id { get; set; }
		public int Quantity { get; set; }

		public Int64 Equipment_id { get; set; }
		public Int64 Asset_id { get; set; }

		public virtual Equipment Equipment { get; set; }
		public virtual Asset Asset { get; set; }

		public Purchase(Int64 id, int quantity, Equipment equipment, Asset asset,
		                Int64 equipment_id, Int64 asset_id)
		{
			Id = id;
			Quantity = quantity;
			Asset = asset;
			Equipment = equipment;
			Equipment_id = equipment_id;
			Asset_id = asset_id;
		}
	}
}