//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using MySql.Data.MySqlClient;
using System;
using Model;
using System.Collections.Generic;

namespace Model
{
	[Serializable]
	public class Service
	{	
		public Int64 Id { get; set; }
		public string Title { get; set; } 
		public decimal Price { get; set; } 
		public int Period { get; set; }
		public int PeriodsPaid { get; set; }
		public decimal Effectiveness { get; set; }
		public bool isNew { get; private set; }

		public Int64 Enterprise_id { get; set; }
		public Int64 Company_id { get; set; }

		public virtual Company Company { get; set; }

		public Service(Int64 id, string title, decimal price, int period,int periodsPaid, 
		               decimal effectiveness, Int64 enterprise_id, Int64 company_id, bool isNew)
		{
			Id = id;
			Title = title;
			Price = price;
			Period = period;
			PeriodsPaid = periodsPaid;
			Enterprise_id = enterprise_id;
			Effectiveness = effectiveness;
			Company_id = company_id;
			this.isNew = isNew;
		}
	}
}