//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Model
{
	[Serializable]
	public class Taxation
	{
		public Int64 Id { get; set; }

		public int Taxation_group { get; set; }
		public decimal Max_revenue { get; set; }
		public int Max_employee { get; set; }
		public double VAT { get; set; }
		public double Income_duty { get; set; }
		public bool isNew { get; private set; }

		public Taxation(Int64 id, int taxation_group, decimal max_revenue, 
		                int max_employee, double VAT, double income_duty, bool isNew)
		{
			Id = id;
			Taxation_group = taxation_group;
			Max_revenue = max_revenue;
			Max_employee = max_employee;
			this.VAT = VAT;
			Income_duty = income_duty;
			this.isNew = isNew;
		}
	}
}
