//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Model
{
	public class Team_member
	{
		public int Hours_in_month { get; set; }

		public virtual Employee Employee_id { get; set; }
		public virtual Project Project_id { get; set; }
		
		public Team_member(Employee employee_id, Project project_id, int hours_in_month)
		{
			Hours_in_month = hours_in_month;
			Employee_id = employee_id;
			Project_id = project_id;
		}
	}
}
